# Generated by Django 4.2.7 on 2023-11-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_productreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '✦✧✧✧✧'), (2, '✦✦✧✧✧'), (3, '✦✦✦✧✧'), (4, '✦✦✦✦✧'), (5, '✦✦✦✦✦')], default=None),
        ),
    ]
